### ISSUE TITLE
vaulted shell --asume : panic: runtime error: hash of unhashable type

### ISSUE THREAD

**Issue by ryan-norton** [miquella/vaulted#102]
The following command: `vaulted shell --assume blah` yielded the following error:
```
panic: runtime error: hash of unhashable type request.ErrInvalidParams

goroutine 1 [running]:
main.main()
	github.com/miquella/vaulted/main.go:52 +0xee
```

Circumstances for this error include - no vault name was specified in the command, the arn passed to --assume was invalid, and no credentials were loaded into my environment.

**Comment by miquella** [comment]
The `panic` has been resolved by #113. At least the real error will bubble out now!
