### ISSUE TITLE
populate RPROMPT for zsh users

### ISSUE THREAD

**Issue by aaronshaf** [miquella/vaulted#12]
Compare: https://github.com/zwily/aws-keychain-util/blob/master/bin/aws-creds#L310

`aws_env['RPROMPT'] = "(aws #{item.attributes[:label]})" # zsh only`

This would be helpful :)

**Comment by aaronshaf** [comment]
![please](http://weknowmemes.com/generator/uploads/generated/g1352217865361546904.jpg "Please")

**Comment by miquella** [comment]
Sorry, this is out of scope for vaulted's core functionality. 😞 But you could add an `RPROMPT` environment variable inside your vault, that should have the same effect you're looking for.

As a side-note, we've been discussing creating a contrib repo to host shell integration and augmentations to vaulted's core functionality. That sounds like something that might end up belonging there once we create it.
