### ISSUE TITLE
 When using Yubikey as a MFA device it fails due to the expression pattern

### ISSUE THREAD

**Issue by jahpola-futurice** [miquella/vaulted#138]
Hi,

Yubikey outputs long text strings such as "ccccccjfkljjiuirgugjefkhrvchbcffblfrbgeuhjje"

So when using vaulted it fails with following error
MFA token: ccccccjfkljjiuirgugjefkhrvchbcffblfrbgeuhjje
ValidationError: 2 validation errors detected: Value 'ccccccjfkljjiuirgugjefkhrvchbcffblfrbgeuhjje' at 'tokenCode' failed to satisfy constraint: Member must satisfy regular expression pattern: [\d]*; Value 'ccccccjfkljjiuirgugjefkhrvchbcffblfrbgeuhjje' at 'tokenCode' failed to satisfy constraint: Member must have length less than or equal to 6
	status code: 400, request id: 65dbb944-1ef5-11e9-be35-018bef9a594c

**Comment by miquella** [comment]
Hi @jahpola-futurice,

That error is being returned from the STS API. After a bit of research, it appears U2F keys are presently only supported by the web console.

> AWS currently supports using U2F security keys only in the AWS Management Console. Using U2F security keys for MFA is not currently supported in the AWS CLI and AWS API, or for access to MFA-protected API operations.
— [Supported Configurations for Using U2F Security Keys ](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_u2f_supported_configurations.html#id_credentials_mfa_u2f_cliapi)

So, unfortunately, there's not a way for me to support Yubikeys at the moment. I will certainly give it a shot once they add support though!
