### ISSUE TITLE
proxy ssh-agent is not signing properly

### ISSUE THREAD

**Issue by thekev** [miquella/vaulted#143]
When in a vaulted shell, recent openssh (maybe 7.2 or later - I'm on 7.9) may warn about an invalid signature type during public key signing. With `vaulted shell` active, there is a proxy agent:
`SSH_AUTH_SOCK=/var/folders/gp/99f8pxx135n6rmccgm75vxrr0000gn/T/proxykeyring526739204/listener`

Now during authentication, there is a warning about incorrect signature type when signing with `rsa-sha2-512`, causing ssh client to downgrade to `ssh-rsa`:
```
debug1: Offering public key: /Users/kblackham/.ssh/id_personal RSA SHA256:1z/Lu4E/N5e583eyLMkB0PSpe7kSMww3MnLRiWajhRo agent
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: /Users/kblackham/.ssh/id_personal RSA SHA256:1z/Lu4E/N5e583eyLMkB0PSpe7kSMww3MnLRiWajhRo agent
debug3: sign_and_send_pubkey: RSA SHA256:1z/Lu4E/N5e583eyLMkB0PSpe7kSMww3MnLRiWajhRo
debug3: sign_and_send_pubkey: signing using rsa-sha2-512
agent key RSA SHA256:1z/Lu4E/N5e583eyLMkB0PSpe7kSMww3MnLRiWajhRo returned incorrect signature type
debug3: sign_and_send_pubkey: signing using ssh-rsa
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
```
Loading the same key into the native agent, this warning is gone, and the signature is handled by `rsa-sha2-512` as expected:
`SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.pj0nmc409S/Listeners`
```
debug1: Offering public key: /Users/kblackham/.ssh/id_personal RSA SHA256:1z/Lu4E/N5e583eyLMkB0PSpe7kSMww3MnLRiWajhRo agent
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: /Users/kblackham/.ssh/id_personal RSA SHA256:1z/Lu4E/N5e583eyLMkB0PSpe7kSMww3MnLRiWajhRo agent
debug3: sign_and_send_pubkey: RSA SHA256:1z/Lu4E/N5e583eyLMkB0PSpe7kSMww3MnLRiWajhRo
debug3: sign_and_send_pubkey: signing using rsa-sha2-512
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey). 
```
This occurs for identities already loaded into the system agent being proxied, as well as those added to the proxy agent. I'm thinking `SignWithFlags` needs to be implemented.

**Comment by miquella** [comment]
@thekev: I actually came to the same conclusion when I implemented #144 :smile:

As it turns out, the `ExtendedAgent` interface was added after the proxy agent was implemented in Vaulted, but the way Vaulted interacts with it was critical. I believe this issue is now corrected (via #144) and will be included in the next release.
