### ISSUE TITLE
Failure to start shell in 2.4.0, InvalidParameter error

### ISSUE THREAD

**Issue by joawan** [miquella/vaulted#151]
When starting a shell in 2.4.0 with assume role, it sometimes fail.
Role is assumed and MFA given. Duration is set to 60min.
60 min is up, shell is exited and attempt to start a new shell. The below error is given

InvalidParameter: 1 validation error(s) found.
- minimum field value of 900, AssumeRoleInput.DurationSeconds.

**Comment by miquella** [comment]
Sorry about this! I believe this should be addressed by #152.

**Comment by miquella** [comment]
Vaulted v2.4.1 has been released! Please let me know if this problem persists with the new version.

**Comment by joawan** [comment]
👍 Thanks you for swift handling and thanks for maintaining a great product!

I'll test the new release.

I found a workaround in `--refresh` but now I won't have to.
