### ISSUE TITLE
Research ExitWithErrorCode returns in Spawn.go

### ISSUE THREAD

**Issue by ryan-norton** [miquella/vaulted#173]
Line 22 in spawn.go 

```	session, err := GetSessionWithOptions(store, &s.SessionOptions)
	if err != nil {
		return err
	}
```

should be revisited to confirm that this should be wrapped in `ExitWithErrorCode` like the rest of the returns back to the command launch.

**Comment by miquella** [comment]
I have confirmed that this _should not_ be wrapped in an `ExitWithErrorCode`. This would mask errors such as `vaulted.ErrIncorrectPassword`, causing them to no longer be translated into the correct exit codes (see [`main.go:66`](https://github.com/miquella/vaulted/blob/64034241097437134970655cf76fdfd4f602f0b6/main.go#L60)).
