### ISSUE TITLE
Vaulted shells keep processes going after closing terminal window – macOS Sierra

### ISSUE THREAD

**Issue by ngoue** [miquella/vaulted#45]
Using vaulted on macOS Sierra and I noticed that when I close a terminal window that is running vaulted it prompts me as usual with the message, "Closing this tab will terminate the running processes: vaulted..."  However, after confirming and closing the window, the processes continue to run even though the shell has closed.  I've tried it with a number of different things, including both a python/django webserver as well as a ruby/rails webserver.  They all persist after the window has closed and a simple `ps aux | grep python` (or `grep ruby`) shows remaining processes.

**Comment by tgroshon** [comment]
Appears to be related, but I just ran a `packer build <template>.json` inside a vaulted shell and had something similar to this happen.  The packer build command immediately returned without any output looking like it exited, but when you check the process list (`ps aux`) there is a packer process running.

I've run this command many times the last few months and never faced this behavior until today.  Pretty sure i'm not using vaulted wrong but who knows! haha

**Comment by tgroshon** [comment]
@miquella and @ryan-norton get to work!  CHOP CHOP! 😛

**Comment by tgroshon** [comment]
I work with @ngoue and I am pretty sure we're both on vaulted v2.0.

**Comment by miquella** [comment]
Fixed by #47.

**Comment by tgroshon** [comment]
thx friends \m/
